spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/securecapita
    username: root
    password: Ana926
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true